### ISSUE TITLE
[Question] How does `last` get login and logout time?

### ISSUE THREAD

**Issue by MarcelRobitaille** [upsuper/utmp-rs#4]
Sorry if this is the wrong place for this, but do you happen to know how the `last` command is able to get login and logout times? Do you think this is something you could implement? I noticed that `utmpdump` does not have both, nor does your library. I looked through the `last` source code a bit, but I can't make heads or tails of it.

Similarly, is the `time` in `UserProcess` the login time or logout time?

Thank you

**Comment by upsuper** [comment]
I would recommend you to look at the source code of `last` command. My guess would be that time of `DeadProcess` entry is used to determine the logout time. `UserProcess` entry is generated at login time, so it's likely being the login time.

**Comment by upsuper** [comment]
Actually, it's probably the run level change. I'm not quite familiar with utmp either, to be honest.
