### ISSUE TITLE
Derive Hash for UtmpEntry

### ISSUE THREAD

**Issue by rust1248** [upsuper/utmp-rs#8]
Would you accept a PR that adds `#[derive(Hash)]` on `UtmpEntry`? I need to store them in a `HashMap`

**Comment by upsuper** [comment]
I can accept it, but it doesn't feel to me like a good idea. Would you mind elaborating a bit why you want to store them in a hash map?

**Comment by rust1248** [comment]
I need to know what entry changed between two reads of the file

**Comment by rust1248** [comment]
Maybe I could just use the `time` field and record the last time I read it
